# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'HealthyPet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthyPet
  
  pod 'lottie-ios'

  pod "ToastViewSwift"

  pod "PromiseKit", "~> 6.8"

  pod 'PDFGenerator', '~> 3.1'

  target 'HealthyPetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthyPetUITests' do
    # Pods for testing
  end

end
